// Created automatically by Cursor AI (2025-11-30)
// Feature #10: Email Summary to Stakeholders

"use client";

import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Mail, Loader2, Check, Send, Plus, X, AlertCircle } from "lucide-react";
import type { Clause } from "@/hooks/useAgentStream";

interface EmailRecipient {
  email: string;
  name?: string;
}

interface EmailSummaryProps {
  contractName: string;
  risk: "low" | "medium" | "high" | null;
  clauses: Clause[];
  summary: string | null;
}

export function EmailSummaryButton({ contractName, risk, clauses, summary }: EmailSummaryProps) {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [recipients, setRecipients] = useState<EmailRecipient[]>([{ email: "" }]);
  const [subject, setSubject] = useState(`Contract Analysis: ${contractName}`);
  const [additionalNotes, setAdditionalNotes] = useState("");

  const addRecipient = () => {
    setRecipients([...recipients, { email: "" }]);
  };

  const removeRecipient = (index: number) => {
    setRecipients(recipients.filter((_, i) => i !== index));
  };

  const updateRecipient = (index: number, email: string) => {
    const updated = [...recipients];
    updated[index] = { email };
    setRecipients(updated);
  };

  const generateEmailBody = useCallback(() => {
    const highRiskCount = clauses.filter(c => c.risk === "high").length;
    const mediumRiskCount = clauses.filter(c => c.risk === "medium").length;
    const lowRiskCount = clauses.filter(c => c.risk === "low").length;

    let body = `CONTRACT ANALYSIS SUMMARY\n`;
    body += `${"=".repeat(50)}\n\n`;
    body += `Contract: ${contractName}\n`;
    body += `Overall Risk Level: ${risk?.toUpperCase() || "N/A"}\n`;
    body += `Analysis Date: ${new Date().toLocaleDateString()}\n\n`;
    
    body += `RISK BREAKDOWN\n`;
    body += `${"-".repeat(30)}\n`;
    body += `• High Risk Clauses: ${highRiskCount}\n`;
    body += `• Medium Risk Clauses: ${mediumRiskCount}\n`;
    body += `• Low Risk Clauses: ${lowRiskCount}\n`;
    body += `• Total Clauses Analyzed: ${clauses.length}\n\n`;

    if (summary) {
      body += `EXECUTIVE SUMMARY\n`;
      body += `${"-".repeat(30)}\n`;
      body += `${summary}\n\n`;
    }

    if (highRiskCount > 0) {
      body += `HIGH RISK CLAUSES (Require Attention)\n`;
      body += `${"-".repeat(30)}\n`;
      clauses
        .filter(c => c.risk === "high")
        .forEach((clause, i) => {
          body += `\n${i + 1}. ${clause.title} (${clause.type})\n`;
          body += `   Summary: ${clause.summary}\n`;
          body += `   Why It Matters: ${clause.whyItMatters}\n`;
        });
      body += `\n`;
    }

    if (additionalNotes) {
      body += `ADDITIONAL NOTES\n`;
      body += `${"-".repeat(30)}\n`;
      body += `${additionalNotes}\n\n`;
    }

    body += `${"-".repeat(50)}\n`;
    body += `Generated by ContractCoach AI\n`;
    body += `This analysis is for informational purposes only.\n`;
    body += `Consult with legal counsel for professional advice.`;

    return body;
  }, [contractName, risk, clauses, summary, additionalNotes]);

  const handleSend = async () => {
    const validRecipients = recipients.filter(r => r.email.trim());
    if (validRecipients.length === 0) {
      setError("Please add at least one recipient");
      return;
    }

    setIsSending(true);
    setError(null);

    try {
      // Generate mailto link with all recipients
      const emailBody = generateEmailBody();
      const recipientEmails = validRecipients.map(r => r.email).join(",");
      
      const mailtoLink = `mailto:${recipientEmails}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailBody)}`;
      
      // Open default email client
      window.location.href = mailtoLink;
      
      setSent(true);
      setTimeout(() => {
        setSent(false);
        setIsDialogOpen(false);
      }, 1500);
    } catch (err) {
      setError("Failed to open email client");
    } finally {
      setIsSending(false);
    }
  };

  const isDisabled = !risk || clauses.length === 0;

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={() => setIsDialogOpen(true)}
        disabled={isDisabled}
        className="text-xs"
      >
        {sent ? (
          <>
            <Check className="h-3.5 w-3.5 mr-1.5 text-emerald-500" />
            Email Opened
          </>
        ) : (
          <>
            <Mail className="h-3.5 w-3.5 mr-1.5" />
            Email Summary
          </>
        )}
      </Button>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5 text-primary" />
              Email Analysis to Stakeholders
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* Recipients */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-xs">Recipients</Label>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={addRecipient}
                  className="h-6 text-xs text-primary"
                >
                  <Plus className="h-3 w-3 mr-1" />
                  Add
                </Button>
              </div>
              <div className="space-y-2">
                {recipients.map((recipient, index) => (
                  <div key={index} className="flex gap-2">
                    <Input
                      type="email"
                      placeholder="email@company.com"
                      value={recipient.email}
                      onChange={(e) => updateRecipient(index, e.target.value)}
                      className="h-8 text-xs flex-1"
                    />
                    {recipients.length > 1 && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => removeRecipient(index)}
                        className="h-8 w-8 p-0 text-text-muted hover:text-red-500"
                      >
                        <X className="h-3.5 w-3.5" />
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Subject */}
            <div className="space-y-2">
              <Label className="text-xs">Subject</Label>
              <Input
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="h-8 text-xs"
              />
            </div>

            {/* Preview */}
            <div className="space-y-2">
              <Label className="text-xs">Email Preview</Label>
              <div className="rounded-md bg-bg-subtle/50 border border-border-subtle p-3 space-y-2">
                <div className="flex items-center gap-2">
                  <Badge className={cn(
                    "text-[9px]",
                    risk === "high" && "bg-red-500/10 text-red-500",
                    risk === "medium" && "bg-amber-500/10 text-amber-500",
                    risk === "low" && "bg-emerald-500/10 text-emerald-500"
                  )}>
                    {risk?.toUpperCase()} RISK
                  </Badge>
                  <span className="text-[11px] text-text-muted">
                    {clauses.length} clauses analyzed
                  </span>
                </div>
                <p className="text-xs text-text-secondary line-clamp-3">
                  {summary || "No summary available"}
                </p>
                {clauses.filter(c => c.risk === "high").length > 0 && (
                  <div className="text-[11px] text-red-500">
                    ⚠️ {clauses.filter(c => c.risk === "high").length} high-risk clause(s) identified
                  </div>
                )}
              </div>
            </div>

            {/* Additional Notes */}
            <div className="space-y-2">
              <Label className="text-xs">Additional Notes (optional)</Label>
              <Textarea
                placeholder="Add any context or notes for the recipients..."
                value={additionalNotes}
                onChange={(e) => setAdditionalNotes(e.target.value)}
                className="text-xs resize-none"
                rows={3}
              />
            </div>

            {/* Error */}
            {error && (
              <div className="flex items-center gap-2 text-xs text-red-500">
                <AlertCircle className="h-3.5 w-3.5" />
                {error}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" size="sm" onClick={() => setIsDialogOpen(false)}>
              Cancel
            </Button>
            <Button size="sm" onClick={handleSend} disabled={isSending}>
              {isSending ? (
                <>
                  <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                  Opening...
                </>
              ) : (
                <>
                  <Send className="h-3.5 w-3.5 mr-1.5" />
                  Open in Email
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

