// Created automatically by Cursor AI (2025-11-30)
// Feature #5: One-Click Share with Web Share API

"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { 
  Share2, 
  Copy, 
  Check, 
  Twitter, 
  Linkedin, 
  Mail,
  Link2,
  Download,
  X
} from "lucide-react";
import type { Clause } from "@/hooks/useAgentStream";

interface ShareButtonProps {
  risk: "low" | "medium" | "high" | null;
  clauses: Clause[];
  summary: string | null;
  contractName?: string;
  className?: string;
}

export function ShareButton({
  risk,
  clauses,
  summary,
  contractName = "Contract Analysis",
  className,
}: ShareButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Generate shareable content
  const generateShareText = useCallback(() => {
    const highRisk = clauses.filter(c => c.risk === "high").length;
    const mediumRisk = clauses.filter(c => c.risk === "medium").length;
    const lowRisk = clauses.filter(c => c.risk === "low").length;

    let text = `📋 ${contractName}\n\n`;
    text += `🎯 Overall Risk: ${risk?.toUpperCase() || "Unknown"}\n\n`;
    text += `📊 Clause Breakdown:\n`;
    text += `• ${highRisk} High Risk\n`;
    text += `• ${mediumRisk} Medium Risk\n`;
    text += `• ${lowRisk} Low Risk\n\n`;
    
    if (summary) {
      text += `📝 Summary:\n${summary}\n\n`;
    }

    text += `🔍 Analyzed with ContractCoach AI`;
    
    return text;
  }, [risk, clauses, summary, contractName]);

  // Generate detailed report
  const generateDetailedReport = useCallback(() => {
    let report = `# Contract Analysis Report\n`;
    report += `## ${contractName}\n\n`;
    report += `**Generated:** ${new Date().toLocaleDateString()}\n`;
    report += `**Overall Risk:** ${risk?.toUpperCase() || "Unknown"}\n\n`;
    
    report += `## Executive Summary\n`;
    report += `${summary || "No summary available."}\n\n`;
    
    report += `## Clause Analysis\n\n`;
    
    clauses.forEach((clause, i) => {
      report += `### ${i + 1}. ${clause.title}\n`;
      report += `**Risk Level:** ${clause.risk.toUpperCase()}\n`;
      report += `**Summary:** ${clause.summary}\n`;
      report += `**Why It Matters:** ${clause.whyItMatters}\n`;
      if (clause.suggestedEdit) {
        report += `**Suggested Edit:** ${clause.suggestedEdit}\n`;
      }
      report += `\n`;
    });

    report += `---\n`;
    report += `*Generated by ContractCoach AI*\n`;
    
    return report;
  }, [risk, clauses, summary, contractName]);

  // Copy to clipboard
  const copyToClipboard = useCallback(async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, []);

  // Native share (mobile)
  const nativeShare = useCallback(async () => {
    const text = generateShareText();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: contractName,
          text: text,
        });
      } catch (err) {
        // User cancelled or error
        console.log("Share cancelled");
      }
    } else {
      // Fallback to copy
      copyToClipboard(text);
    }
  }, [generateShareText, contractName, copyToClipboard]);

  // Share to Twitter
  const shareToTwitter = useCallback(() => {
    const text = `📋 Just analyzed a contract with ContractCoach AI!\n\n🎯 Risk Level: ${risk?.toUpperCase()}\n📊 ${clauses.length} clauses reviewed\n\n#ContractCoach #AI #LegalTech`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    window.open(url, "_blank", "width=550,height=420");
  }, [risk, clauses.length]);

  // Share to LinkedIn
  const shareToLinkedIn = useCallback(() => {
    const text = `I just analyzed a contract using ContractCoach AI! The analysis found ${clauses.length} key clauses with an overall ${risk} risk level. AI-powered contract review is the future! 🚀`;
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}&summary=${encodeURIComponent(text)}`;
    window.open(url, "_blank", "width=550,height=420");
  }, [risk, clauses.length]);

  // Email share
  const shareByEmail = useCallback(() => {
    const subject = `Contract Analysis: ${contractName}`;
    const body = generateShareText();
    const url = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = url;
  }, [contractName, generateShareText]);

  // Download report
  const downloadReport = useCallback(() => {
    const report = generateDetailedReport();
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${contractName.replace(/\s+/g, "_")}_Analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generateDetailedReport, contractName]);

  // Don't render if no analysis
  if (!risk || clauses.length === 0) {
    return null;
  }

  return (
    <div className={cn("relative", className)}>
      <Button
        variant="outline"
        size="sm"
        onClick={() => setIsOpen(!isOpen)}
        className="h-8 px-3 text-xs"
      >
        <Share2 className="h-3.5 w-3.5 mr-1.5" />
        Share
      </Button>

      <AnimatePresence>
        {isOpen && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-40"
              onClick={() => setIsOpen(false)}
            />

            {/* Dropdown */}
            <motion.div
              initial={{ opacity: 0, y: -10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10, scale: 0.95 }}
              className="absolute right-0 top-full mt-2 z-50 w-64 bg-bg-elevated border border-border-subtle rounded-lg shadow-lg overflow-hidden"
            >
              {/* Header */}
              <div className="flex items-center justify-between px-3 py-2 border-b border-border-subtle/50 bg-bg-subtle/30">
                <span className="text-xs font-medium text-text-primary">Share Analysis</span>
                <button
                  onClick={() => setIsOpen(false)}
                  className="p-1 rounded hover:bg-bg-subtle transition-colors"
                >
                  <X className="h-3 w-3 text-text-muted" />
                </button>
              </div>

              {/* Options */}
              <div className="p-2 space-y-1">
                {/* Copy Summary */}
                <button
                  onClick={() => {
                    copyToClipboard(generateShareText());
                  }}
                  className="w-full flex items-center gap-3 px-3 py-2 rounded-md hover:bg-bg-subtle transition-colors text-left"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-emerald-500" />
                  ) : (
                    <Copy className="h-4 w-4 text-text-muted" />
                  )}
                  <div>
                    <p className="text-xs font-medium text-text-primary">
                      {copied ? "Copied!" : "Copy Summary"}
                    </p>
                    <p className="text-[11px] text-text-muted">Copy analysis to clipboard</p>
                  </div>
                </button>

                {/* Copy Link */}
                <button
                  onClick={() => copyToClipboard(window.location.href)}
                  className="w-full flex items-center gap-3 px-3 py-2 rounded-md hover:bg-bg-subtle transition-colors text-left"
                >
                  <Link2 className="h-4 w-4 text-text-muted" />
                  <div>
                    <p className="text-xs font-medium text-text-primary">Copy Link</p>
                    <p className="text-[11px] text-text-muted">Share page URL</p>
                  </div>
                </button>

                <div className="h-px bg-border-subtle/50 my-2" />

                {/* Social sharing */}
                <div className="flex items-center gap-2 px-3 py-2">
                  <button
                    onClick={shareToTwitter}
                    className="flex-1 flex items-center justify-center gap-1.5 px-2 py-1.5 rounded bg-[#1DA1F2]/10 hover:bg-[#1DA1F2]/20 transition-colors"
                  >
                    <Twitter className="h-3.5 w-3.5 text-[#1DA1F2]" />
                    <span className="text-[11px] font-medium text-[#1DA1F2]">Twitter</span>
                  </button>
                  <button
                    onClick={shareToLinkedIn}
                    className="flex-1 flex items-center justify-center gap-1.5 px-2 py-1.5 rounded bg-[#0A66C2]/10 hover:bg-[#0A66C2]/20 transition-colors"
                  >
                    <Linkedin className="h-3.5 w-3.5 text-[#0A66C2]" />
                    <span className="text-[11px] font-medium text-[#0A66C2]">LinkedIn</span>
                  </button>
                </div>

                {/* Email */}
                <button
                  onClick={shareByEmail}
                  className="w-full flex items-center gap-3 px-3 py-2 rounded-md hover:bg-bg-subtle transition-colors text-left"
                >
                  <Mail className="h-4 w-4 text-text-muted" />
                  <div>
                    <p className="text-xs font-medium text-text-primary">Email</p>
                    <p className="text-[11px] text-text-muted">Send via email client</p>
                  </div>
                </button>

                <div className="h-px bg-border-subtle/50 my-2" />

                {/* Download */}
                <button
                  onClick={downloadReport}
                  className="w-full flex items-center gap-3 px-3 py-2 rounded-md hover:bg-bg-subtle transition-colors text-left"
                >
                  <Download className="h-4 w-4 text-text-muted" />
                  <div>
                    <p className="text-xs font-medium text-text-primary">Download Report</p>
                    <p className="text-[11px] text-text-muted">Save as Markdown file</p>
                  </div>
                </button>

                {/* Native share (mobile) */}
                {typeof navigator !== "undefined" && typeof navigator.share === "function" && (
                  <>
                    <div className="h-px bg-border-subtle/50 my-2" />
                    <button
                      onClick={nativeShare}
                      className="w-full flex items-center gap-3 px-3 py-2 rounded-md bg-primary/10 hover:bg-primary/20 transition-colors text-left"
                    >
                      <Share2 className="h-4 w-4 text-primary" />
                      <div>
                        <p className="text-xs font-medium text-primary">Share...</p>
                        <p className="text-[11px] text-primary/70">Open system share menu</p>
                      </div>
                    </button>
                  </>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}

// Quick copy button (simpler version)
export function QuickCopyButton({
  text,
  className,
}: {
  text: string;
  className?: string;
}) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <button
      onClick={copy}
      className={cn(
        "p-1.5 rounded transition-all",
        copied 
          ? "bg-emerald-500/10 text-emerald-500" 
          : "hover:bg-bg-subtle text-text-muted hover:text-text-primary",
        className
      )}
      title={copied ? "Copied!" : "Copy to clipboard"}
    >
      {copied ? (
        <Check className="h-3.5 w-3.5" />
      ) : (
        <Copy className="h-3.5 w-3.5" />
      )}
    </button>
  );
}

